import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  autoGenerated: [{ type: 'autogenerated', dirName: '.' }],
  windows: [
    {
      type: 'category',
      label: 'Windows Documentation',
      items: [
        {
          type: 'category',
          label: 'WSL Documentation',
          items: [
            'windows/WSL/index',
            {
              type: 'category',
              label: 'Overview',
              items: [
                'windows/WSL/about',
                'windows/WSL/compare-versions',
                'windows/WSL/basic-commands',
              ],
            },
            {
              type: 'category',
              label: 'Install',
              items: [
                'windows/WSL/install',
                'windows/WSL/install-manual',
                'windows/WSL/install-on-server',
              ],
            },
            {
              type: 'category',
              label: 'Tutorials',
              items: [
                'windows/WSL/setup/environment',
                'windows/WSL/tutorials/wsl-vscode',
                'windows/WSL/tutorials/wsl-git',
                'windows/WSL/tutorials/wsl-database',
                'windows/WSL/tutorials/wsl-containers',
                // '/cpp/build/walkthrough-build-debug-wsl2',
                'windows/WSL/tutorials/gpu-compute',
                'windows/WSL/tutorials/gui-apps',
                // '/windows/dev-environment/javascript/nodejs-on-wsl',
                'windows/WSL/tutorials/linux',
              ],
            },
            {
              type: 'category',
              label: 'Concepts',
              items: [
                'windows/WSL/filesystems',
                'windows/WSL/wsl-config',
                'windows/WSL/file-permissions',
                'windows/WSL/networking',
                'windows/WSL/systemd',
              ],
            },
            {
              type: 'category',
              label: 'How-to',
              items: [
                'windows/WSL/use-custom-distro',
                'windows/WSL/build-custom-distro',
                'windows/WSL/wsl2-mount-disk',
                'windows/WSL/connect-usb',
                'windows/WSL/case-sensitivity',
                'windows/WSL/disk-space',
                'windows/WSL/wsl-plugins',
              ],
            },
            {
              type: 'category',
              label: 'Enterprise security',
              items: [
                'windows/WSL/enterprise',
                'windows/WSL/intune',
              ],
            },
            'windows/WSL/faq',
            'windows/WSL/troubleshooting',
            {
              type: 'category',
              label: 'Release Notes',
              items: [
                'windows/WSL/release-notes',
                'windows/WSL/kernel-release-notes',
                'windows/WSL/store-release-notes',
              ],
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
