import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  autoGenerated: [{ type: 'autogenerated', dirName: '.' }],
  windows: [
    {
      type: 'category',
      label: 'Windows',
      items: [
        {
          type: 'category',
          label: 'WSL',
          link: {
            type: 'doc',
            id: 'windows/wsl/index',
          },
          items: [
            {
              type: 'category',
              label: '概述',
              items: [
                'windows/wsl/about',
                'windows/wsl/compare-versions',
                'windows/wsl/basic-commands',
              ],
            },
            {
              type: 'category',
              label: '安装',
              items: [
                'windows/wsl/install',
                'windows/wsl/install-manual',
                'windows/wsl/install-on-server',
              ],
            },
            {
              type: 'category',
              label: '教程',
              items: [
                'windows/wsl/setup/environment',
                'windows/wsl/tutorials/wsl-vscode',
                'windows/wsl/tutorials/wsl-git',
                'windows/wsl/tutorials/wsl-database',
                'windows/wsl/tutorials/wsl-containers',
                // '/cpp/build/walkthrough-build-debug-wsl2',
                'windows/wsl/tutorials/gpu-compute',
                'windows/wsl/tutorials/gui-apps',
                // '/windows/dev-environment/javascript/nodejs-on-wsl',
                'windows/wsl/tutorials/linux',
              ],
            },
            {
              type: 'category',
              label: '概念',
              items: [
                'windows/wsl/filesystems',
                'windows/wsl/wsl-config',
                'windows/wsl/file-permissions',
                'windows/wsl/networking',
                'windows/wsl/systemd',
              ],
            },
            {
              type: 'category',
              label: '如何做',
              items: [
                'windows/wsl/use-custom-distro',
                'windows/wsl/build-custom-distro',
                'windows/wsl/wsl2-mount-disk',
                'windows/wsl/connect-usb',
                'windows/wsl/case-sensitivity',
                'windows/wsl/disk-space',
                'windows/wsl/wsl-plugins',
              ],
            },
            {
              type: 'category',
              label: '企业安全',
              items: [
                'windows/wsl/enterprise',
                'windows/wsl/intune',
              ],
            },
            'windows/wsl/faq',
            'windows/wsl/troubleshooting',
            {
              type: 'category',
              label: '发行说明',
              items: [
                'windows/wsl/release-notes',
                'windows/wsl/kernel-release-notes',
                'windows/wsl/store-release-notes',
              ],
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
